# Generated by Django 5.1 on 2025-09-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=255)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
