# Generated by Django 5.1 on 2025-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_soccerfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
