# Generated by Django 5.1 on 2025-09-13 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_public_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Match date & time')),
                ('match_type', models.CharField(choices=[('5v5', '5 vs 5'), ('7v7', '7 vs 7'), ('8v8', '8 vs 8')], default='5v5', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='available', max_length=20)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.soccerfield')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_matches', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='joined_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-datetime'],
            },
        ),
    ]
